[build]
  command = "npm run start"
  publish = "public"  

[functions]
  node_bundler = "esbuild"
  directory = "./functions"
  external_node_modules = ["pdf-parse"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

